# Site settings
title: juanmiguelruadev - Software developer
description: "A blog about lorem ipsum ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://juanmiguelrua.com" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: juanmiguelRua.Dev
user_title: Software Engineer
email: me@juanmiguelrua.com
twitter_username: \@JuanMiguelRua
github_username:  juanmiguelRuaDev

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: juanmirua
    url: https://github.com/juanmiguelRuaDev/juanmiguelRuaDev.github.io
  - name: personal-web
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
